# Master

# Set if data should be exported
EXPORT <- T

CLEAN_NET_DAILY_MOVEMENT            <- T
CLEAN_OD_CONNECTION_MATRIX          <- F
CLEAN_DIR_REGIONAL_PAIR_CONNECTIONS <- F
CLEAN_MEDIAN_DISTANCE_TRAVELED      <- F
CLEAN_UNIQUE_RESIDENTS              <- F
CLEAN_UNIQUE_SUBSCRIBERS            <- F

